#!/usr/bin/env node

/*
  Auto-generates src/icons.js from SVG files in assets/
  - Recursively scans the assets directory for .svg files
  - Reads each file as UTF-8 string
  - Escapes content safely using JSON.stringify for valid JS string literals
  - Writes an ES module exporting an `icons` object and default export

  Usage: node scripts/generate-icons.js
*/

const fs = require('fs/promises');
const path = require('path');

const ASSETS_DIR = path.resolve(__dirname, '..', 'assets');
const OUTPUT_FILE = path.resolve(__dirname, '..', 'src', 'icons.js');

async function* walk(dir) {
  const entries = await fs.readdir(dir, { withFileTypes: true });
  for (const entry of entries) {
    const fullPath = path.join(dir, entry.name);
    if (entry.isDirectory()) {
      yield* walk(fullPath);
    } else if (entry.isFile()) {
      yield fullPath;
    }
  }
}

function toKey(fromPath) {
  // Create a stable key based on path relative to ASSETS_DIR, without extension
  const rel = path.relative(ASSETS_DIR, fromPath).split(path.sep).join('/');
  const noExt = rel.replace(/\.svg$/i, '');
  return noExt; // keep subpath structure with forward slashes
}

async function buildIcons() {
  const icons = {};

  const sanitizeSVG = (raw) => {
    // Remove XML declaration and DOCTYPE which can break innerHTML in HTML documents
    let s = raw.replace(/^\s*<\?xml[^>]*>\s*/i, "");
    s = s.replace(/<!DOCTYPE[^>]*>\s*/gi, "");
    // Optional: strip comments at start
    s = s.replace(/^\s*<!--([\s\S]*?)-->\s*/g, "");
    return s.trim();
  };

  try {
    for await (const filePath of walk(ASSETS_DIR)) {
      if (!filePath.toLowerCase().endsWith('.svg')) continue;
      const key = toKey(filePath);
      const content = await fs.readFile(filePath, 'utf8');
      const sanitized = sanitizeSVG(content);
      // Use JSON.stringify to safely embed as JS string literal
      icons[key] = JSON.stringify(sanitized);
    }
  } catch (err) {
    console.error('Error reading assets:', err);
    process.exit(1);
  }

  const keys = Object.keys(icons).sort();
  const entries = keys
    .map((k) => `  ${JSON.stringify(k)}: ${icons[k]}`)
    .join(',\n');

  const header = `/*
  AUTO-GENERATED FILE - DO NOT EDIT
  Generated by scripts/generate-icons.js
*/`;

  const fileContent = `${header}\n\nexport const icons = {\n${entries}\n};\n\nexport default icons;\n`;

  await fs.mkdir(path.dirname(OUTPUT_FILE), { recursive: true });
  await fs.writeFile(OUTPUT_FILE, fileContent, 'utf8');
}

buildIcons().catch((err) => {
  console.error(err);
  process.exit(1);
});
